spring:
  application:
    name: eureka
server:
  port: 8089
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:8089/eureka